pipeline {
    agent any
    environment {
        IMAGE_NAME = "nodejs-app"
        CONTAINER_NAME = "nodejs-container"
    }
    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }
        stage('Run Container') {
            steps {
                sh 'docker run -d --rm --name $CONTAINER_NAME -p 3000:3000 $IMAGE_NAME'
            }
        }
    }
    post {
        always {
            sh 'docker stop $CONTAINER_NAME || true'
        }
    }
}
